---
- name: init docker swarm
  docker_swarm:
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    state: present
  register: init_swarm

- name: join token
  set_fact:
    join_token_worker: "{{ init_swarm.swarm_facts.JoinTokens.Worker }}"
