---
- name: "Download wordpress"
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: "Extract wordpress"
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes

- name: "Copy wordpress config"
  copy:
    src: "{{ wp_install_dit }}/wp-config-sample.php"
    dest: "{{ wp_install_dit }}/wp-config.php"
    remote_src: yes

- name: "Change wordpress config"
  replace:
    path: "{{ wp_install_dit }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: "localhost", value: "{{ wp_db_ip }}" }
    - { regex: "database_name_here", value: "{{ wp_db_name }}" }
    - { regex: "username_here", value: "{{ wp_username }}" }
    - { regex: "password_here", value: "{{ wp_user_password }}" }

- name: "Config apache"
  template:
    src: templates/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify:
    - restart apache
