---
- name: join in a swarm cluster
  docker_swarm:
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    join_token: "{{ hostvars[groups['docker'][0]].join_token_worker }}"
    remote_addrs: "{{ docker_swarm_manager_ip }}"
    state: join
