---
- name: Install dependencies
  apt:
    name:
      - mysql-server
      - python3-mysqldb
    state: latest
    update_cache: yes

- name: Create database
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    encoding: utf8
    collation: utf8_general_ci
    state: present

- name: Create database user
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - "{{ wp_host_ip }}"

- name: "Config mysql"
  copy:
    src: files/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
    - restart mysql
