---
- hosts: docker
  become: yes
  roles:
    - docker_swarm_manager

- hosts: docker_workers
  become: yes
  roles:
    - docker_swarm_worker

- hosts: docker
  become: yes
  roles:
    - deploy_stack
