---
- name: copy docker-compose to remote host
  copy:
    src: "docker-compose.yml"
    dest: "/opt/docker-compose.yml"

- name: deploy stack
  docker_stack:
    name: express-app
    compose:
      - "/opt/docker-compose.yml"
    state: present
